---
etcd_ca_conf_directory:  /opt/certs

# etcd version
etcd_version: "3.4.0"
# Directroy for etcd configuration
etcd_conf_dir: "/etc/etcd"
# Directory to store downloaded etcd archive
# Should not be deleted to avoid downloading over and over again
etcd_download_dir: "/opt/etcd"
# Directroy to store etcd binaries
etcd_bin_dir: "/usr/local/bin"
# etcd data directory (etcd database files so to say)
etcd_data_dir: "/var/lib/etcd"

# Certificate authority and certificate files for etcd
etcd_certificates:
  - ca.pem
  - kubernetes.pem
  - kubernetes-key.pem
